$(document).ready(
		function(){
			$('div#hCalendarControls>div').mousedown(
					//为id hCalendarControls的div元素所包含的每一个直接子元素div挂钩了mousedown事件
					function(){
						if(!$(this).hasClass('hCalendarSeparator')){
							$(this).html('<div></div>');
							$(this).prev().html('<div></div>');
							$(this).next().html('<div></div>');
						}
					}
			).mouseup(
					function(){
						if(!$(this).hasClass('hCalendarSeparator')){
							if($(this).hasClass('hCalendarControlToggle')){
								$('div#hCalendarControls div').not(this).empty();
								$(this).find('div').addClass('hCalendarControlOn');//find方法搜索后代元素div，返回对象
								$(this).prev().html('<div></div>');
								$(this).next().html('<div></div>');
							}
							else{
								$(this).empty();
								if(!$(this).prev().prev().find('div').length){
									$(this).prev().empty();
								}
								if(!$(this).next().next().find('div').length){
									$(this).next().empty();
								}
								var $isNext = ($(this).attr('id').indexOf('next')!=-1);
								$('div#hCalendar').load(
										'Example%207-2%20'+($isNext?'Next':'Previous')+'.html'
								);
							}
						}
					}
			);
			$('td.hCalendarDay').mouseover(
					function(){
						$(this).addClass('mouseOn');
					}
			).mouseout(
					function(){
						$(this).removeClass('mouseOn');
					}
			);
			$.getScript(
					'Figure 7-5.js',
					function(){
						$('table.hCalendar td').click(
								function(){
									$(this)
									.animate({backgroundColor:'lightgrey'},1000)
									.animate({backgroundColor:'lightblue'},1000);
								}
						);
					}
			);
		}
);
